apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: my-frontend
          image: my-frontend-image
