apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    env: production
  name: my-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      labels:
        env: production
    spec:
      containers:
      - image: my-frontend-image
        name: my-frontend
