apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-private
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: my-service-name
          servicePort: 3333
        path: /*
