---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: orgname
spec:
  storageClassName: orgname
  capacity:
    storage: 1m
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: orgname
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: orgname
rules: 
  - resources: 
    - persistentvolumes
    apiGroups:
    - v1
    resourceNames: 
    - orgname
    verbs: [get]
