nameReference:
- kind: PersistentVolume
  version: v1
  fieldSpecs:
  - path: rules/resourceNames
    kind: ClusterRole

- kind: StorageClass
  version: v1
  group: storage.k8s.io
  fieldSpecs:
  - path: spec/storageClassName
    kind: PersistentVolume
  - path: rules/resourceNames
    kind: ClusterRole
