resources:
  - configmap.yaml
  - ingress.yaml
  - service.yaml

configurations:
- kustomizeconfig.yaml

vars:
  - name: CNAME
    objref:
      apiVersion: apps/v1
      kind: Ingress
      name: my-ingress
    fieldref:
      fieldpath: spec.rules[0].host
