apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s.permanent.cloud/appInstallation.id: add961a2-b5c7-4ccd-b3c7-66f7c03c9c6e
  name: ai-zv58kz2nbox64fkrqptr94nurvqoxz88o52etherpad
  namespace: cstmr-72n16kk2an86kc4855ujzk9a9plo293274l
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etherpad
      k8s.permanent.cloud/appInstallation.id: add961a2-b5c7-4ccd-b3c7-66f7c03c9c6e
  template:
    metadata:
      labels:
        app: etherpad
        k8s.permanent.cloud/appInstallation.id: add961a2-b5c7-4ccd-b3c7-66f7c03c9c6e
    spec:
      containers:
      - env:
        - name: ETHERPAD_DB_TYPE
          value: mysql
        - name: ETHERPAD_DB_HOST
          value: ai-zv58kz2nbox64fkrqptr94nurvqoxz88o52etherpad-mysql
        - name: ETHERPAD_DB_DATABASE
          value: etherpad_lite_db
        - name: ETHERPAD_DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: etherpad-mysql-auth
        - name: ETHERPAD_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: etherpad-mysql-auth
        image: etherpad/etherpad:latest
        name: etherpad
        ports:
        - containerPort: 9001
          name: web
        volumeMounts:
        - mountPath: /opt/etherpad-lite/settings.json
          name: config
          subPath: settings.json
        - mountPath: /opt/etherpad/settings.json
          name: config
          subPath: settings.json
      volumes:
      - configMap:
          name: ai-zv58kz2nbox64fkrqptr94nurvqoxz88o52etherpad
        name: config
