apiVersion: v1
data:
  init.sql: |
    create database `etherpad_lite_db`;
    use `etherpad_lite_db`;

    CREATE TABLE `store` (
      `key` varchar(100) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
      `value` longtext COLLATE utf8mb4_bin NOT NULL,
      PRIMARY KEY (`key`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
kind: ConfigMap
metadata:
  labels:
    k8s.permanent.cloud/appInstallation.id: 45170c85-ec8b-4008-9d57-4524aa16f93f
  name: ai-w613mmojuo0qqir4pvc1l4rsr96mm6110ymetherpad-mysql-init
  namespace: cstmr-zvyjvn35b81rkfkr87fznrpanw5op9x5yo0
