apiVersion: v1
kind: Service
metadata:
  labels:
    k8s.permanent.cloud/appInstallation.id: 45170c85-ec8b-4008-9d57-4524aa16f93f
  name: ai-w613mmojuo0qqir4pvc1l4rsr96mm6110ymetherpad
  namespace: cstmr-zvyjvn35b81rkfkr87fznrpanw5op9x5yo0
spec:
  ports:
  - name: web
    port: 80
    targetPort: web
  selector:
    app: etherpad
    k8s.permanent.cloud/appInstallation.id: 45170c85-ec8b-4008-9d57-4524aa16f93f
